name: tests

on: [push]

jobs:
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: xcodebuild -showdestinations -scheme "PegGame Watch App" -project PegGame/PegGame.xcodeproj
    # - run: >
    #     xcodebuild test -scheme "PegGame Watch App" 
    #     -project PegGame/PegGame.xcodeproj 
    #     -destination "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm)" 
    #     | xcpretty && exit ${PIPESTATUS[0]}
