name: tests

on: [push]

jobs:
  run_tests:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: >
        xcodebuild test -scheme "PegGame Watch App" 
        -project PegGame/PegGame.xcodeproj
        -destination 'id=097E6079-06FA-4817-8CF8-8A0F68B6DD5E'
