name: tests

on: [push]

jobs:
  run_tests:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Show destinations
      run: >
        xcodebuild -showdestinations 
        -scheme "PegGame Watch App" 
        -project PegGame/PegGame.xcodeproj
    - name: Run tests
      run: >
        xcodebuild test -scheme "PegGame Watch App" 
        -project PegGame/PegGame.xcodeproj
        -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15 Pro'
        
  # -destination 'platform=watchOS Simulator,OS=10.4,name=Apple Watch Series 9 (45mm)'
